import { Fund } from '../types';

export const SAMPLE_FUNDS: Fund[] = [
  {
    id: 'fund_001',
    name: 'Global Equity Growth Fund',
    category: 'Equity',
    description: 'A diversified equity fund focusing on global growth opportunities with emphasis on technology and healthcare sectors.',
    minimumInvestment: 1000,
    currentNAV: 156.78,
    oneYearReturn: 12.5,
    threeYearReturn: 15.2,
    fiveYearReturn: 18.7,
    riskLevel: 'Medium',
    fundManager: 'Sarah Johnson',
    inceptionDate: new Date('2018-03-15'),
    totalAssets: 2500000000,
    expenseRatio: 0.75,
    benchmark: 'MSCI World Index',
  },
  {
    id: 'fund_002',
    name: 'Emerging Markets Fund',
    category: 'Equity',
    description: 'High-growth potential fund investing in emerging market economies with focus on Asia-Pacific region.',
    minimumInvestment: 2500,
    currentNAV: 89.45,
    oneYearReturn: 8.3,
    threeYearReturn: 22.1,
    fiveYearReturn: 16.8,
    riskLevel: 'High',
    fundManager: 'David Chen',
    inceptionDate: new Date('2017-08-20'),
    totalAssets: 1800000000,
    expenseRatio: 1.25,
    benchmark: 'MSCI Emerging Markets Index',
  },
  {
    id: 'fund_003',
    name: 'Conservative Bond Fund',
    category: 'Debt',
    description: 'A stable income fund investing in high-grade government and corporate bonds with low volatility.',
    minimumInvestment: 500,
    currentNAV: 23.67,
    oneYearReturn: 4.2,
    threeYearReturn: 5.1,
    fiveYearReturn: 4.8,
    riskLevel: 'Low',
    fundManager: 'Michael Rodriguez',
    inceptionDate: new Date('2015-01-10'),
    totalAssets: 3200000000,
    expenseRatio: 0.45,
    benchmark: 'Bloomberg Aggregate Bond Index',
  },
  {
    id: 'fund_004',
    name: 'Technology Innovation Fund',
    category: 'Sectoral',
    description: 'Focused on disruptive technology companies including AI, blockchain, and renewable energy sectors.',
    minimumInvestment: 5000,
    currentNAV: 234.12,
    oneYearReturn: 28.7,
    threeYearReturn: 35.4,
    fiveYearReturn: 42.1,
    riskLevel: 'High',
    fundManager: 'Lisa Wang',
    inceptionDate: new Date('2019-06-01'),
    totalAssets: 1200000000,
    expenseRatio: 1.15,
    benchmark: 'NASDAQ Technology Index',
  },
  {
    id: 'fund_005',
    name: 'Balanced Hybrid Fund',
    category: 'Hybrid',
    description: 'A balanced approach combining equity and debt instruments for moderate risk and steady returns.',
    minimumInvestment: 1000,
    currentNAV: 67.89,
    oneYearReturn: 9.8,
    threeYearReturn: 11.3,
    fiveYearReturn: 12.6,
    riskLevel: 'Medium',
    fundManager: 'Robert Thompson',
    inceptionDate: new Date('2016-11-25'),
    totalAssets: 2800000000,
    expenseRatio: 0.85,
    benchmark: 'S&P 500 60% + Bond Index 40%',
  },
  {
    id: 'fund_006',
    name: 'ELSS Tax Saver Fund',
    category: 'ELSS',
    description: 'Equity Linked Savings Scheme with tax benefits under Section 80C and 3-year lock-in period.',
    minimumInvestment: 500,
    currentNAV: 45.32,
    oneYearReturn: 14.2,
    threeYearReturn: 16.8,
    fiveYearReturn: 19.3,
    riskLevel: 'Medium',
    fundManager: 'Priya Sharma',
    inceptionDate: new Date('2014-04-01'),
    totalAssets: 1600000000,
    expenseRatio: 1.05,
    benchmark: 'Nifty 50 Index',
  },
  {
    id: 'fund_007',
    name: 'International Diversified Fund',
    category: 'International',
    description: 'Global diversification across developed markets in US, Europe, and Japan with currency hedging.',
    minimumInvestment: 3000,
    currentNAV: 178.56,
    oneYearReturn: 6.7,
    threeYearReturn: 13.9,
    fiveYearReturn: 14.2,
    riskLevel: 'Medium',
    fundManager: 'James Anderson',
    inceptionDate: new Date('2017-02-14'),
    totalAssets: 980000000,
    expenseRatio: 1.35,
    benchmark: 'MSCI World ex-India Index',
  },
  {
    id: 'fund_008',
    name: 'Healthcare Sector Fund',
    category: 'Sectoral',
    description: 'Specialized fund focusing on pharmaceutical, biotechnology, and medical device companies.',
    minimumInvestment: 2000,
    currentNAV: 123.45,
    oneYearReturn: 19.4,
    threeYearReturn: 24.7,
    fiveYearReturn: 21.8,
    riskLevel: 'High',
    fundManager: 'Dr. Emily Carter',
    inceptionDate: new Date('2018-09-10'),
    totalAssets: 750000000,
    expenseRatio: 1.45,
    benchmark: 'Healthcare Sector Index',
  },
  {
    id: 'fund_009',
    name: 'Index Fund 500',
    category: 'Index',
    description: 'Low-cost passive fund tracking the performance of top 500 companies with minimal expense ratio.',
    minimumInvestment: 100,
    currentNAV: 98.76,
    oneYearReturn: 11.2,
    threeYearReturn: 13.8,
    fiveYearReturn: 15.1,
    riskLevel: 'Medium',
    fundManager: 'Automated Management',
    inceptionDate: new Date('2013-07-01'),
    totalAssets: 5200000000,
    expenseRatio: 0.25,
    benchmark: 'S&P 500 Index',
  },
  {
    id: 'fund_010',
    name: 'Green Energy Thematic Fund',
    category: 'Thematic',
    description: 'ESG-focused fund investing in renewable energy, clean technology, and sustainable businesses.',
    minimumInvestment: 2500,
    currentNAV: 87.23,
    oneYearReturn: 16.8,
    threeYearReturn: 25.3,
    fiveYearReturn: 28.9,
    riskLevel: 'High',
    fundManager: 'Mark Williams',
    inceptionDate: new Date('2020-01-15'),
    totalAssets: 450000000,
    expenseRatio: 1.25,
    benchmark: 'Clean Energy Index',
  },
];

export const getFundById = (id: string): Fund | undefined => {
  return SAMPLE_FUNDS.find(fund => fund.id === id);
};

export const getFundsByCategory = (category: string): Fund[] => {
  return SAMPLE_FUNDS.filter(fund => fund.category === category);
};

export const getFundsByRiskLevel = (riskLevel: 'Low' | 'Medium' | 'High'): Fund[] => {
  return SAMPLE_FUNDS.filter(fund => fund.riskLevel === riskLevel);
};

export const getTopPerformingFunds = (count: number = 5): Fund[] => {
  return SAMPLE_FUNDS
    .sort((a, b) => b.oneYearReturn - a.oneYearReturn)
    .slice(0, count);
};
